language: java
notifications:
  hipchat:
    rooms:
      secure: FJRsjBoDqxAnuLpBJ/Iq9jQ94qAMy1GUPSQzAvPB3v7TuvDXS4tEkWSwqbV5Mg644kjR1+bz0HqH+ByO+UzrC9pv1h4dhsX4daKk94kZAjQIgT004L2b+SGqOqxhJwf0j9bz2RFi4y3+0gsyd/O+E9qNemwZ87uTexLtLEXbE0Dzrx2ZEjYcB1rIyYQmNs3KLuY8DVkoMD5PfHKBHFR6dsQ8EEqhzoaHLEV71Jl8QckQXQFRxNLMLjK0fGxO2NA6AZrykp8JskfUQR4c15TqLpBd+QsL9xNWTgukAZf6wiE11xZ8EBSXqr9F59c7Noqi9LQvE+TaJcHaSlYfZ/AnyHssh2ifQIyfSqkz6XoIFEDffPJin8s6etFrPHTCrkY0yD69ysxVNpuqr6gZePd1KDtMnqNdpJOzUWWNdivgpHDEcp/Gm40/qsyhL41iUcgssfiQow6JwmwTtx3cRZAGdMMtQudCsiKmJ8IAaEhnTykF3JWsGUyEIzalMGxE03PXYtXdDpx6gv8i6F6zy1rpZtNffScAHtm3VhWifFGX7QemF3JwlrDZc/GdAC8eeL85ZxhEsSdJxyBDpoIEvOEt4rWNY4rL48c1ksr3nqvSi62D6I7Di5g5Td9zm2Nhb1Hac2kDKlLlsD36nkx663HifPCAWqCTssoqJ/+CcO63yLE=
deploy:
  provider: releases
  api_key:
    secure: oc2I2X4d15OZpqZ5bxyw9c2Ra/S1hpX/d865ijP0BU9zXkaI5qmM9Xvg6lsxGCzQtWpMIiFVvZUxV6QP7W4hA3OWAvCrfesVpWpOZ3AIb7NuUunLbYXehWGH5nX9rUmbuVpRb1KIuoDCgBr4jKEonOZxV1V5+49K7fXwx5TOgwhyqtxZXFsdMD1YhPXaOeF8y3tusPiZx7lH/qTYXoPV8mec5nt8rIWJiX3yZnAQ61DI9N7KMsYysptPQi84ZVCmelw6QStN4Opi5j2/lDJlwDky4/ZyY7VQ/6jVc7/Iq8nXIplEkyG8DhNN9LRoMoUETznM6cW6whrCZAS9n8WJEX84Pkj04/X4xrDfZlFcnLnZu0qBOAbN0I+zlpzYcWr/ShcLiWqbV9LDl165d+Z0airqy7p6B+xrG8YnMj6lEa1RoaVCknz2OVVfwJwURtEfvfLBxH8cYWyrgWxBarnJb71F9DxOEQsUfwfqoZ7YullWmabOC/Qkr7CiB5IIb78PU/RcPnRNA4q9eCcVJmtjQb1EtvAeTjZF/AUVuCkXYME4nJYZfyBnjhM6q0CrbZ+rHJfQCPyKTzrHiH6X3JuIU3l7/caJsZJiAphQ6TikBm5GO3i0CRRA/56YXmJnCic4UuV5o4aEyTY53Qf0yiJJS0l+5/nAbFev0+HAPYlqS30=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-was-profile-plugin
